name: Deploy POC

on:
  workflow_dispatch:
    inputs:
      resourcePrefix:
        default: 'poc'
        required: true
        description: 'Resource Prefix'
      clusterName:
        default: 'poc'
        required: true
        description: 'Name of the AKS Cluster'
      aksAdminGroupNames:
        default: 'poc'
        required: true
        description: 'Comma-separated list of AAD groups'

jobs:
  deploy-poc:
    runs-on: ubuntu-22.04
    steps:
      - uses: