name: Deploy POC

on:
  workflow_dispatch:
    inputs:
      resourcePrefix:
        default: 'contoso'
        required: true
        description: 'Resource Prefix'
      clusterName:
        default: 'aks'
        required: true
        description: 'Name of the AKS Cluster'
      aksAdminGroupNames:
        required: false
        description: 'Comma-separated list of AAD groups'
      location:
        required: true
        type: choice
        description: 'Resource Location'
        default: westus2
        options:
          - westus2
          - canadacentral

jobs:
  deploy-poc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Resource Group Name
        run: |
          let "randomIdentifier=$RANDOM*$RANDOM"
          echo "resourceGroupName=poc-autoscaling-gh-$randomIdentifier" >> $GITHUB_ENV
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch AKS Admin Group IDs
        uses: Azure/cli@v1
        env:
          AKS_ADMIN_GROUP_NAMES: ${{ github.event.inputs.aksAdminGroupNames }}
        with:
          # Specify the script here
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/fetch-ad-group-ids.sh
            $GITHUB_WORKSPACE/scripts/fetch-ad-group-ids.sh
      - name: Validate Bicep Templates
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
        with:
          inlineScript: |
            az deployment sub validate \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs${{ env.adminGroupObjectIDs }}

      - name: Run a Dry-Run Deployment
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
        with:
          inlineScript: |
            az deployment sub create \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs${{ env.adminGroupObjectIDs }} \
              --what-if

      - name: Deploy AKS
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
        with:
          inlineScript: |
            az deployment sub create \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs${{ env.adminGroupObjectIDs }}
