name: Deploy POC

on:
  workflow_dispatch:
    inputs:
      resourcePrefix:
        default: 'contoso'
        required: true
        description: 'Resource Prefix'
      clusterName:
        default: 'aks'
        required: true
        description: 'Name of the AKS Cluster'
      aksAdminGroupIds:
        required: false
        description: 'Comma-separated list of AAD group IDs'
      location:
        required: true
        type: choice
        description: 'Resource Location'
        default: westus2
        options:
          - westus2
          - canadacentral

jobs:
  deploy-poc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Resource Group Name
        run: |
          let "randomIdentifier=$RANDOM*$RANDOM"
          echo "randomIdentifier=$randomIdentifier" >> $GITHUB_ENV 
          echo "resourceGroupName=poc-autoscaling-gh-$randomIdentifier" >> $GITHUB_ENV

      - name: Parse AAD Group IDs to Json
        env:
          AKS_ADMIN_GROUP_IDS: ${{ github.event.inputs.aksAdminGroupIds }}
        run: |
          adGroupIds=$(echo $AKS_ADMIN_GROUP_IDS | tr "," "\n")
          adGroupIdsJson=$(jq -n --arg inarr "${adGroupIds}" '$inarr | split("\n")' --compact-output)
          echo $adGroupIdsJson > $GITHUB_WORKSPACE/adGroupIds.json

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Templates
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
        with:
          inlineScript: |
            az deployment sub validate \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json

      - name: Run a Dry-Run Deployment
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
        with:
          inlineScript: |
            az deployment sub create \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json \
              --what-if

      - name: Deploy AKS
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
        with:
          inlineScript: |
            az deployment sub create \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./deploy/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json
