name: Deploy POC

on:
  workflow_dispatch:
    inputs:
      resourcePrefix:
        default: 'contoso'
        required: true
        description: 'Resource Prefix'
      clusterName:
        default: 'aks'
        required: true
        description: 'Name of the AKS Cluster'
      aksAdminGroupIds:
        required: false
        description: 'Comma-separated list of AAD group IDs'
      location:
        required: true
        type: choice
        description: 'Resource Location'
        default: westus2
        options:
          - westus2
          - canadacentral
      
jobs:
  deploy-poc:
    name: 'Deploy POC'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Resource Group Name
        id: generate
        run: |
          let "randomIdentifier=$RANDOM*$RANDOM"
          echo "randomIdentifier=$randomIdentifier" >> $GITHUB_ENV 
          echo "resourceGroupName=poc-autoscaling-gh-$randomIdentifier" >> $GITHUB_ENV

      - name: Parse AAD Group IDs to Json
        id: parse
        env:
          AKS_ADMIN_GROUP_IDS: ${{ github.event.inputs.aksAdminGroupIds }}
        run: |
          adGroupIds=$(echo $AKS_ADMIN_GROUP_IDS | tr "," "\n")
          adGroupIdsJson=$(jq -n --arg inarr "${adGroupIds}" '$inarr | split("\n")' --compact-output)
          echo $adGroupIdsJson > $GITHUB_WORKSPACE/adGroupIds.json

      - name: Login to Azure
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Templates
        id: validate
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
          NODE_ADMIN_PASSWORD: ${{ secrets.NODE_ADMIN_PASSWORD }}
        with:
          inlineScript: |
            az deployment sub validate \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./infrastructure/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json \
              --parameters nodeAdminPassword=$NODE_ADMIN_PASSWORD

      - name: Run a Dry-Run Deployment
        id: dryrun
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
          NODE_ADMIN_PASSWORD: ${{ secrets.NODE_ADMIN_PASSWORD }}
        with:
          inlineScript: |
            az deployment sub create \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./infrastructure/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json \
              --parameters nodeAdminPassword=$NODE_ADMIN_PASSWORD \
              --what-if
      - name: Deploy AKS
        id: deploy
        uses: Azure/cli@v1
        env:
          DEPLOY_LOCATION: ${{ github.event.inputs.location }}
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
          NODE_ADMIN_PASSWORD: ${{ secrets.NODE_ADMIN_PASSWORD }}
        with:
          inlineScript: |
            az deployment sub create \
              --name poc-deployment-$RANDOM_IDENTIFIER \
              --template-file ./infrastructure/aks/main.bicep \
              --location $DEPLOY_LOCATION \
              --parameters resourcePrefix=${{ github.event.inputs.resourcePrefix }} \
              --parameters resourceGroupName=${{ env.resourceGroupName }} \
              --parameters clusterName=${{ github.event.inputs.clusterName }} \
              --parameters adminGroupObjectIDs=@$GITHUB_WORKSPACE/adGroupIds.json \
              --parameters nodeAdminPassword=$NODE_ADMIN_PASSWORD \

            echo "::set-output name=clusterName::$(az deployment sub show -n poc-deployment-$RANDOM_IDENTIFIER --query properties.outputs.clusterName.value -o tsv)"
            echo "::set-output name=registryName::$(az deployment sub show -n poc-deployment-$RANDOM_IDENTIFIER --query properties.outputs.registryName.value -o tsv)"

      - name: Import Required Container Images to Private Registry
        id: push_image
        uses: Azure/cli@v1
        env:
          RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
          REGISTRY_NAME: ${{ steps.deploy.outputs.registryName }}
        with:
          inlineScript: |
            az acr import \
                        --name $REGISTRY_NAME \
                        --source quay.io/jetstack/cert-manager-controller:v1.8.0 \
                        --image jetstack/cert-manager-controller:v1.8.0

            az acr import \
                        --name $REGISTRY_NAME \
                        --source quay.io/brancz/kube-rbac-proxy:v0.10.0 \
                        --image brancz/kube-rbac-proxy:v0.10.0

            az acr import \
                        --name $REGISTRY_NAME \
                        --source quay.io/jetstack/cert-manager-webhook:v1.8.0 \
                        --image jetstack/cert-manager-webhook:v1.8.0

            az acr import \
                        --name $REGISTRY_NAME \
                        --source quay.io/jetstack/cert-manager-cainjector:v1.8.0 \
                        --image jetstack/cert-manager-cainjector:v1.8.0

            az acr import \
                        --name $REGISTRY_NAME \
                        --source quay.io/jetstack/cert-manager-ctl:v1.8.0 \
                        --image jetstack/cert-manager-ctl:v1.8.0

            az acr import \
                        --name $REGISTRY_NAME \
                        --source docker.io/summerwind/actions-runner:latest \
                        --image summerwind/actions-runner:latest
            
            az acr import \
                        --name $REGISTRY_NAME \
                        --source docker.io/summerwind/actions-runner-controller:v0.24.0 \
                        --image summerwind/actions-runner-controller:v0.24.0

      - name: Configure Actions Runner Controller
        id: configure
        env:
          CLUSTER_NAME: ${{ steps.deploy.outputs.clusterName }}
          RESOURCE_GROUP: ${{ env.resourceGroupName }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_INSTALLATION_ID: ${{ secrets.GH_INSTALLATION_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          REGISTRY_NAME: ${{ steps.deploy.outputs.registryName }}
        run: |
          az aks wait --exists --timeout 240 --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP 
          az aks wait --created --timeout 240 --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP 
          az aks get-credentials --admin --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP
          
          helm repo add jetstack https://charts.jetstack.io
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          
          helm repo update

          helm install \
                    cert-manager jetstack/cert-manager \
                    --namespace cert-manager \
                    --create-namespace \
                    --version v1.8.0 \
                    --set installCRDs=true \
                    --set image.repository=$REGISTRY_NAME.azurecr.io/jetstack/cert-manager-controller \
                    --set webhook.image.repository=$REGISTRY_NAME.azurecr.io/jetstack/cert-manager-webhook \
                    --set cainjector.image.repository=$REGISTRY_NAME.azurecr.io/jetstack/cert-manager-cainjector \
                    --set startupapicheck.image.repository=$REGISTRY_NAME.azurecr.io/jetstack/cert-manager-ctl \
                    --set startupapicheck.timeout=5m

          helm upgrade --install \
                       --namespace actions-runner-system \
                       --create-namespace \
                       --set image.repository=$REGISTRY_NAME.azurecr.io/summerwind/actions-runner-controller \
                       --set image.tag=v0.24.0 \
                       --set image.actionsRunnerRepositoryAndTag=$REGISTRY_NAME.azurecr.io/summerwind/actions-runner:latest \
                       --set authSecret.github_app_id=$GH_APP_ID \
                       --set authSecret.github_app_installation_id=$GH_INSTALLATION_ID \
                       --set authSecret.github_app_private_key="$GH_PRIVATE_KEY" \
                       --set metrics.proxy.image.repository=$REGISTRY_NAME.azurecr.io/brancz/kube-rbac-proxy \
                       --set metrics.proxy.image.tag=v0.10.0 \
                       --wait actions-runner-controller \
                       actions-runner-controller/actions-runner-controller
          
          # kubectl create secret generic controller-manager \
          #       -n actions-runner-system \
          #       --from-literal=github_app_id=$GH_APP_ID \
          #       --from-literal=github_app_installation_id=$GH_INSTALLATION_ID \
          #       --from-literal=github_app_private_key="$GH_PRIVATE_KEY"

          kubectl apply -f ./infrastructure/github/runner.yml

      # - name: Destroy AKS
      #   if: ${{ failure() && (steps.deploy.conclusion == 'failure' || steps.configure.conclusion == 'failure') || cancelled() && steps.deploy.conclusion == 'success' }}
      #   uses: Azure/cli@v1
      #   env:
      #     RANDOM_IDENTIFIER: ${{ env.randomIdentifier }}
      #     RESOURCE_GROUP: ${{ env.resourceGroupName }}
      #   with:
      #     inlineScript: |
      #       az group delete \
      #         --resource-group $RESOURCE_GROUP \
      #         --yes \
      #         --only-show-errors

