name: Use Autoscaled Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build using Self-hosted Runner'
    runs-on: aks-runner
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
